name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - uses: astral-sh/setup-uv@v6

      - name: Run the example with uv
        run: uv run se-for-sci-example-2

